### PR TITLE
Update software.md

### PR DESCRIPTION
**Pull request by ceola2022**
Added Pro Edition for Eclipse Mosquitto (Server).
The issue with the wrong logo persists.
Please let me know how I can fix it.

Thank you,
Olga

### CODE REVIEW

**Comment by B-Weiss** [comment]
> Added Pro Edition for Eclipse Mosquitto (Server). The issue with the wrong logo persists. Please let me know how I can fix it.
> 
> Thank you, Olga

Same here as for your earlier PR. I can not reproduce your issue with the logo. The one shown next to your description is clearly Mosquitto. I´m fine with approving both PRs and publish your changes.

Burkhard

**Comment by ceola2022** [comment]
> > Added Pro Edition for Eclipse Mosquitto (Server). The issue with the wrong logo persists. Please let me know how I can fix it.
> > Thank you, Olga
> 
> Same here as for your earlier PR. I can not reproduce your issue with the logo. The one shown next to your description is clearly Mosquitto. I´m fine with approving both PRs and publish your changes.
> 
> Burkhard

Great! Thank you very much!

**Comment by ceola2022** [comment]
> > > Added Pro Edition for Eclipse Mosquitto (Server). The issue with the wrong logo persists. Please let me know how I can fix it.
> > > Thank you, Olga
> > 
> > 
> > Same here as for your earlier PR. I can not reproduce your issue with the logo. The one shown next to your description is clearly Mosquitto. I´m fine with approving both PRs and publish your changes.
> > Burkhard
> 
> Great! Thank you very much!

Hi Burkhard,

It seems we added the two versions onto the Cloud Broker page listing.
But one of them has to go to the Server broker page listing.

Can you please move it there?

image

**Comment by ceola2022** [comment]
Sorry @B-Weiss for bothering you again,

But the **Cloud** version is in the **Server listing** now.

Can you please move the **Cloud** version to the **Cloud broker listing**?

**Comment by B-Weiss** [comment]
Sure, it´s done

**Comment by B-Weiss** [comment]
Hi Olga, 

To me it looks like Server is in the right place, but Cloud should go under "Cloud Brokers", right?

Regards
Burkhard

Burkhard Weiss | Corporate Designer
——
phone +49 871 97 50 63 26 | mobile +49 160 69 24 24 5
HiveMQ GmbH | Ergoldinger Str. 2a | 84030 Landshut | Germany
Registered as HiveMQ GmbH | Registergericht Landshut | HRB 8906
Geschäftsführer: Christian Götz | Dominik Obermaier

**Comment by ceola2022** [comment]
Hi Burkhard,

I have just received this message from you though we have already sorted
out the issue.
Everything is good!

Thank you one more time for your help!

Sincerely,
Olga

**Pull request merged**
