### PR TITLE
Update software.md

### PR DESCRIPTION
**Pull request by ceola2022**
Hello!
My name is Olga and I am a Marketing Specialist at Cedalo GmbH. We are offering a Pro version of Mosquitto open source product.

I added the description of the cloud version here. But we also have a server version, it is just I do not get how to add it.

I also wanted to re-use the Mosquitto logo, but for some reason I can see the MQTT net logo next to my description (though in code I have referred to the Mosquitto logo).

Please help!

### CODE REVIEW

**Comment by zzj1993** [comment]
已收到您的邮件~

**Comment by TanNingMeng** [comment]
感谢您的来信，我会尽快阅读的。- 致敬 谭建程

**Comment by B-Weiss** [comment]
> Hello! My name is Olga and I am a Marketing Specialist at Cedalo GmbH. We are offering a Pro version of Mosquitto open source product.
> 
> I added the description of the cloud version here. But we also have a server version, it is just I do not get how to add it.
> 
> I also wanted to re-use the Mosquitto logo, but for some reason I can see the MQTT net logo next to my description (though in code I have referred to the Mosquitto logo).
> 
> Please help!

Hello Olga, 
your PR looks fine to me, I can not reproduce the issue you are having with the MQTTnet logo.

**Comment by ceola2022** [comment]
> > Hello! My name is Olga and I am a Marketing Specialist at Cedalo GmbH. We are offering a Pro version of Mosquitto open source product.
> > I added the description of the cloud version here. But we also have a server version, it is just I do not get how to add it.
> > I also wanted to re-use the Mosquitto logo, but for some reason I can see the MQTT net logo next to my description (though in code I have referred to the Mosquitto logo).
> > Please help!
> 
> Hello Olga, your PR looks fine to me, I can not reproduce the issue you are having with the MQTTnet logo.

Great! Thanks, then please merge it :)

**Pull request merged**
